@startuml
'https://plantuml.com/class-diagram

interface WidgetFactory {
    Button createButton()
    Label createLabel()
}

class WindowsWidgetFactory implements WidgetFactory {
    WindowsButton createButton()
    WindowsLabel createLabel()
}
note left of WindowsWidgetFactory: Only knows about\nWindows widgets

class MacosWidgetFactory implements WidgetFactory {
    MacosButton createButton()
    MacosLabel createLabel()
}
note right of MacosWidgetFactory: Only knows about\nMacOS widgets

@enduml