@startuml
'https://plantuml.com/class-diagram

interface Widget {
    void draw()
}

interface Button extends Widget {
    void disable()
}

interface Label extends Widget

class WindowsButton implements Button {
    void draw()
    void disable()
}
class MacosButton implements Button {
    void draw()
    void disable()
}

class WindowsLabel implements Label {
    void draw()
}
class MacosLabel implements Label {
    void draw()
}


@enduml